services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.63.0
    ports:
      - "16686:16686"
      # - "4317:4317"
      # - "4318:4318"
    environment:
      - LOG_LEVEL=debug
    networks:
      - jaeger-net

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.114.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      # - "8888:8888"   # Prometheus metrics exposed by the collector
      # - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - jaeger
    networks:
      - jaeger-net

  # Redis for our services
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge
